const SIGN_UP = 'SIGN_UP';
const LOG_IN = 'LOG_IN';
const LOG_IN_ERROR = 'LOG_IN_ERROR';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
const GET_MENU = 'GET_MENU';
const GET_MENU_ERROR = 'GET_MENU_ERROR';
const PLACE_AN_ORDER = 'PLACE_AN_ORDER';
const PLACE_AN_ORDER_ERROR = 'PLACE_AN_ORDER_ERROR';
const ADD_TO_CART = 'ADD_TO_CART';
const SET_CART = 'SET_CART';
const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
const GET_ORDERS = 'GET_ORDERS';
const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
const UPDATE_ORDER = "UPDATE_ORDER";  
const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";




export {
    SIGN_UP,
    LOG_IN,
    LOG_IN_ERROR,
    SIGN_UP_ERROR,
    GET_MENU,
    GET_MENU_ERROR,
    PLACE_AN_ORDER,
    PLACE_AN_ORDER_ERROR,
    ADD_TO_CART,
    ADD_TO_CART_ERROR,
    SET_CART,
    GET_ORDERS,
    GET_ORDERS_ERROR,
    UPDATE_ORDER,
    UPDATE_ORDER_ERROR
}